/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as LevantamentosIndexRouteImport } from './routes/levantamentos.index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as PreencherTokenRouteImport } from './routes/preencher.$token'
import { Route as LevantamentosNovoRouteImport } from './routes/levantamentos.novo'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as LevantamentosIdIndexRouteImport } from './routes/levantamentos.$id.index'
import { Route as LevantamentosIdResumoRouteImport } from './routes/levantamentos.$id.resumo'
import { Route as ConfiguracoesTiposTypeIdRouteImport } from './routes/configuracoes.tipos.$typeId'
import { Route as ClientesIdLevantamentosSurveyIdRouteImport } from './routes/clientes.$id.levantamentos.$surveyId'
import { Route as ClientesIdDadosAmbientaisRecordIdRouteImport } from './routes/clientes.$id.dados-ambientais.$recordId'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo.$'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosIndexRoute = LevantamentosIndexRouteImport.update({
  id: '/levantamentos/',
  path: '/levantamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreencherTokenRoute = PreencherTokenRouteImport.update({
  id: '/preencher/$token',
  path: '/preencher/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosNovoRoute = LevantamentosNovoRouteImport.update({
  id: '/levantamentos/novo',
  path: '/levantamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosIdIndexRoute = LevantamentosIdIndexRouteImport.update({
  id: '/levantamentos/$id/',
  path: '/levantamentos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevantamentosIdResumoRoute = LevantamentosIdResumoRouteImport.update({
  id: '/levantamentos/$id/resumo',
  path: '/levantamentos/$id/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesTiposTypeIdRoute =
  ConfiguracoesTiposTypeIdRouteImport.update({
    id: '/tipos/$typeId',
    path: '/tipos/$typeId',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ClientesIdLevantamentosSurveyIdRoute =
  ClientesIdLevantamentosSurveyIdRouteImport.update({
    id: '/levantamentos/$surveyId',
    path: '/levantamentos/$surveyId',
    getParentRoute: () => ClientesIdRoute,
  } as any)
const ClientesIdDadosAmbientaisRecordIdRoute =
  ClientesIdDadosAmbientaisRecordIdRouteImport.update({
    id: '/dados-ambientais/$recordId',
    path: '/dados-ambientais/$recordId',
    getParentRoute: () => ClientesIdRoute,
  } as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/levantamentos/novo': typeof LevantamentosNovoRoute
  '/preencher/$token': typeof PreencherTokenRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/levantamentos/': typeof LevantamentosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/configuracoes/tipos/$typeId': typeof ConfiguracoesTiposTypeIdRoute
  '/levantamentos/$id/resumo': typeof LevantamentosIdResumoRoute
  '/levantamentos/$id/': typeof LevantamentosIdIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/clientes/$id/dados-ambientais/$recordId': typeof ClientesIdDadosAmbientaisRecordIdRoute
  '/clientes/$id/levantamentos/$surveyId': typeof ClientesIdLevantamentosSurveyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/levantamentos/novo': typeof LevantamentosNovoRoute
  '/preencher/$token': typeof PreencherTokenRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/levantamentos': typeof LevantamentosIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/configuracoes/tipos/$typeId': typeof ConfiguracoesTiposTypeIdRoute
  '/levantamentos/$id/resumo': typeof LevantamentosIdResumoRoute
  '/levantamentos/$id': typeof LevantamentosIdIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/clientes/$id/dados-ambientais/$recordId': typeof ClientesIdDadosAmbientaisRecordIdRoute
  '/clientes/$id/levantamentos/$surveyId': typeof ClientesIdLevantamentosSurveyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes/$id': typeof ClientesIdRouteWithChildren
  '/levantamentos/novo': typeof LevantamentosNovoRoute
  '/preencher/$token': typeof PreencherTokenRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/levantamentos/': typeof LevantamentosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/configuracoes/tipos/$typeId': typeof ConfiguracoesTiposTypeIdRoute
  '/levantamentos/$id/resumo': typeof LevantamentosIdResumoRoute
  '/levantamentos/$id/': typeof LevantamentosIdIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
  '/clientes/$id/dados-ambientais/$recordId': typeof ClientesIdDadosAmbientaisRecordIdRoute
  '/clientes/$id/levantamentos/$surveyId': typeof ClientesIdLevantamentosSurveyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/login'
    | '/manutencao'
    | '/reset-password'
    | '/clientes/$id'
    | '/levantamentos/novo'
    | '/preencher/$token'
    | '/projetos/$id'
    | '/clientes/'
    | '/configuracoes/'
    | '/levantamentos/'
    | '/projetos/'
    | '/configuracoes/tipos/$typeId'
    | '/levantamentos/$id/resumo'
    | '/levantamentos/$id/'
    | '/api/public/photo/$'
    | '/clientes/$id/dados-ambientais/$recordId'
    | '/clientes/$id/levantamentos/$surveyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manutencao'
    | '/reset-password'
    | '/clientes/$id'
    | '/levantamentos/novo'
    | '/preencher/$token'
    | '/projetos/$id'
    | '/clientes'
    | '/configuracoes'
    | '/levantamentos'
    | '/projetos'
    | '/configuracoes/tipos/$typeId'
    | '/levantamentos/$id/resumo'
    | '/levantamentos/$id'
    | '/api/public/photo/$'
    | '/clientes/$id/dados-ambientais/$recordId'
    | '/clientes/$id/levantamentos/$surveyId'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/login'
    | '/manutencao'
    | '/reset-password'
    | '/clientes/$id'
    | '/levantamentos/novo'
    | '/preencher/$token'
    | '/projetos/$id'
    | '/clientes/'
    | '/configuracoes/'
    | '/levantamentos/'
    | '/projetos/'
    | '/configuracoes/tipos/$typeId'
    | '/levantamentos/$id/resumo'
    | '/levantamentos/$id/'
    | '/api/public/photo/$'
    | '/clientes/$id/dados-ambientais/$recordId'
    | '/clientes/$id/levantamentos/$surveyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManutencaoRoute: typeof ManutencaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ClientesIdRoute: typeof ClientesIdRouteWithChildren
  LevantamentosNovoRoute: typeof LevantamentosNovoRoute
  PreencherTokenRoute: typeof PreencherTokenRoute
  ProjetosIdRoute: typeof ProjetosIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  LevantamentosIndexRoute: typeof LevantamentosIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  LevantamentosIdResumoRoute: typeof LevantamentosIdResumoRoute
  LevantamentosIdIndexRoute: typeof LevantamentosIdIndexRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos/': {
      id: '/levantamentos/'
      path: '/levantamentos'
      fullPath: '/levantamentos/'
      preLoaderRoute: typeof LevantamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preencher/$token': {
      id: '/preencher/$token'
      path: '/preencher/$token'
      fullPath: '/preencher/$token'
      preLoaderRoute: typeof PreencherTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos/novo': {
      id: '/levantamentos/novo'
      path: '/levantamentos/novo'
      fullPath: '/levantamentos/novo'
      preLoaderRoute: typeof LevantamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos/$id/': {
      id: '/levantamentos/$id/'
      path: '/levantamentos/$id'
      fullPath: '/levantamentos/$id/'
      preLoaderRoute: typeof LevantamentosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levantamentos/$id/resumo': {
      id: '/levantamentos/$id/resumo'
      path: '/levantamentos/$id/resumo'
      fullPath: '/levantamentos/$id/resumo'
      preLoaderRoute: typeof LevantamentosIdResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/tipos/$typeId': {
      id: '/configuracoes/tipos/$typeId'
      path: '/tipos/$typeId'
      fullPath: '/configuracoes/tipos/$typeId'
      preLoaderRoute: typeof ConfiguracoesTiposTypeIdRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/clientes/$id/levantamentos/$surveyId': {
      id: '/clientes/$id/levantamentos/$surveyId'
      path: '/levantamentos/$surveyId'
      fullPath: '/clientes/$id/levantamentos/$surveyId'
      preLoaderRoute: typeof ClientesIdLevantamentosSurveyIdRouteImport
      parentRoute: typeof ClientesIdRoute
    }
    '/clientes/$id/dados-ambientais/$recordId': {
      id: '/clientes/$id/dados-ambientais/$recordId'
      path: '/dados-ambientais/$recordId'
      fullPath: '/clientes/$id/dados-ambientais/$recordId'
      preLoaderRoute: typeof ClientesIdDadosAmbientaisRecordIdRouteImport
      parentRoute: typeof ClientesIdRoute
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
  ConfiguracoesTiposTypeIdRoute: typeof ConfiguracoesTiposTypeIdRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
  ConfiguracoesTiposTypeIdRoute: ConfiguracoesTiposTypeIdRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface ClientesIdRouteChildren {
  ClientesIdDadosAmbientaisRecordIdRoute: typeof ClientesIdDadosAmbientaisRecordIdRoute
  ClientesIdLevantamentosSurveyIdRoute: typeof ClientesIdLevantamentosSurveyIdRoute
}

const ClientesIdRouteChildren: ClientesIdRouteChildren = {
  ClientesIdDadosAmbientaisRecordIdRoute:
    ClientesIdDadosAmbientaisRecordIdRoute,
  ClientesIdLevantamentosSurveyIdRoute: ClientesIdLevantamentosSurveyIdRoute,
}

const ClientesIdRouteWithChildren = ClientesIdRoute._addFileChildren(
  ClientesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  LoginRoute: LoginRoute,
  ManutencaoRoute: ManutencaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ClientesIdRoute: ClientesIdRouteWithChildren,
  LevantamentosNovoRoute: LevantamentosNovoRoute,
  PreencherTokenRoute: PreencherTokenRoute,
  ProjetosIdRoute: ProjetosIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  LevantamentosIndexRoute: LevantamentosIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  LevantamentosIdResumoRoute: LevantamentosIdResumoRoute,
  LevantamentosIdIndexRoute: LevantamentosIdIndexRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
